### ISSUE TITLE
TypeError: stylelint.createLinter(...).getConfigForFile is not a function

### ISSUE THREAD

**Issue by fcollonval** [prettier/stylelint-config-prettier#135] opened 2022-11-08 13:31 UTC
When using the cli `stylelint-config-prettier-check`, there is the following error:

```sh
TypeError: stylelint.createLinter(...).getConfigForFile is not a function
    at check (/home/fcollonval/tmp/myextension/node_modules/stylelint-config-prettier/src/checker.js:14:4)
    at Object.<anonymous> (/home/fcollonval/tmp/myextension/node_modules/stylelint-config-prettier/bin/check.js:5:1)
```

See: https://github.com/jupyterlab/extension-cookiecutter-ts/actions/runs/3418643040/jobs/5693550762

Versions installed:

```
stylelint-config-prettier@^9.0.3:
  version "9.0.3"
--
stylelint-config-recommended@^6.0.0:
  version "6.0.0"
--
stylelint-config-standard@~24.0.0:
  version "24.0.0"
--
stylelint-prettier@^2.0.0:
  version "2.0.0"
--
stylelint@^14.3.0:
  version "14.14.1"
```

**Comment by shannonmoeller** [comment] 2022-11-08 17:17
Thanks for the details. Closing as duplicate of #134, but this info was helpful.

**Closed by shannonmoeller** 2022-11-08 17:17 UTC
